name: Playwright Python Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install Playwright browsers
          python -m playwright install --with-deps

      - name: Run Playwright Tests with pytest
        run: |
          pytest tests/ --junitxml=test-results/junit-report.xml --html=test-results/report.html --self-contained-html

      - name: Upload Test Report (JUnit)
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-results/junit-report.xml

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: test-results/report.html

      # ✅ TestDino Integration
      - name: Send TestDino report
        run: |
         npx --yes tdpw ./playwright-report \
           --token="${{ secrets.TESTDINO_TOKEN }}" \
           --upload-html \
           --verbose
